# Generated by Django 5.1.5 on 2025-01-24 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0014_ingredient_product_ingredients'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='ingredients',
            field=models.ManyToManyField(blank=True, to='store.ingredient'),
        ),
    ]
